apiVersion: v1
kind: PersistentVolume
metadata:
  name: cbr-checkpoints-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/cbr-news/checkpoints
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cbr-checkpoints-pvc
  namespace: cbr-news
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cbr-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/cbr-news/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cbr-data-pvc
  namespace: cbr-news
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
